version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
