name: EDK2

on:
  push:
    branches: [ main ]
    tags-ignore: [ '**' ]
    paths:
    - '.github/workflows/edk2.yml'
    - 'edk2/**'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./edk2

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
            build-essential \
            git \
            iasl \
            nasm \
            python-is-python3 \
            uuid-dev

    - name: Download EDK2
      run: git clone --recursive --depth 1 -b edk2-stable202411 https://github.com/tianocore/edk2.git ./sdk

    - name: Build EDK2
      working-directory: ./edk2/sdk
      run: make -C BaseTools

    - name: Setup Packages
      working-directory: ./edk2/sdk
      run: |
        ln -s ${GITHUB_WORKSPACE}/edk2/CountDown MdeModulePkg/Application/CountDown
        ls -l MdeModulePkg/Application/CountDown
        sed MdeModulePkg/MdeModulePkg.dsc -i -e '/^\[Components\]/aMdeModulePkg/Application/CountDown/CountDown.inf/'

    - name: Create Artifacts
      working-directory: ./edk2/sdk
      run: |
        mkdir ${GITHUB_WORKSPACE}/edk2/artifacts

        source edksetup.sh

        build \
            --platform=MdeModulePkg/MdeModulePkg.dsc \
            --module=MdeModulePkg/Application/CountDown/CountDown.inf \
            --arch=X64 \
            --buildtarget=RELEASE \
            --tagname=GCC5
        cp Build/MdeModule/RELEASE_GCC5/X64/CountDown.efi ${GITHUB_WORKSPACE}/edk2/artifacts/

        EDK2_TARGET=$(git tag --points-at HEAD)
        echo "EDK2_TARGET=${EDK2_TARGET}" >> $GITHUB_ENV

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.EDK2_TARGET }}
        path: edk2/artifacts/
        retention-days: 1
